-- ============================================================
-- V10__analysis_task.sql · H2
-- 图来源分析任务：对某来源（可多来源合并）发起的一次分析留痕
-- ============================================================

CREATE TABLE analysis_task (
  id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connector_id     BIGINT       NOT NULL,   -- 首个来源连接器 id（过滤/兼容单来源）
  connector_ids    VARCHAR(500),            -- 多来源合并时的全部来源 id（逗号分隔）
  connector_name   VARCHAR(255),            -- 来源名快照（删库后仍可显示）
  task_type        VARCHAR(20)  NOT NULL,   -- ENGINE/LLM
  status           VARCHAR(20)  NOT NULL DEFAULT 'RUNNING', -- RUNNING/SUCCESS/FAILED
  draft_snapshot   TEXT,                    -- 草稿/细化结果 JSON
  error_message    VARCHAR(500),
  operator         VARCHAR(100),
  created_at       DATETIME     NOT NULL,
  finished_at      DATETIME
);
CREATE INDEX idx_task_connector ON analysis_task (connector_id);
CREATE INDEX idx_task_created   ON analysis_task (created_at);
CREATE INDEX idx_task_status    ON analysis_task (status);
