-- ============================================================
-- V1__init.sql · H2 2.x 建表迁移（Flyway，库以 MODE=MySQL 连接运行）
-- 来源：《数据关联与业务流程监控分析平台-项目文档书-v1.0》附录 A：数据模型 DDL
-- 内容：21 张表（建模域 / 监控域 / 配置域 / 接入域 / 系统域），与 MySQL 版同构
-- 翻译规则：
--   1) id BIGINT AUTO_INCREMENT → id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY，删除原 PRIMARY KEY (id) 行
--   2) KEY idx_xxx (...) → 独立语句 CREATE INDEX idx_xxx ON 表名 (...);
--   3) UNIQUE KEY uk_xxx (...) → 表内联约束 CONSTRAINT uk_xxx UNIQUE (...)
--   4) JSON 列（ext/params/value/content/detail）→ TEXT
--   5) 删除表选项 ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
--   6) 复合主键（route_node、sys_user_role）原样保留
-- ============================================================

-- ==================== 建模域 ====================

-- 站点节点（系统/库表/部门岗位/业务动作/制造设备等）
CREATE TABLE node (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  node_type     VARCHAR(20)  NOT NULL,  -- SYSTEM/SUBSYSTEM/DATABASE/TABLE/DEPARTMENT/ROLE/ACTION/EVENT/DEVICE/WORKSTATION
  name          VARCHAR(100) NOT NULL,  -- 显示名（主别名）
  code          VARCHAR(50),            -- 唯一编码
  sub_type      VARCHAR(50),            -- 库类型 MYSQL/ORACLE/REDIS... 或系统类别
  ip            VARCHAR(100),
  level         VARCHAR(4)   DEFAULT 'L3',  -- L1核心/L2重要/L3普通/L4一般
  status        VARCHAR(20)  DEFAULT 'ACTIVE',
  owner         VARCHAR(50),            -- 责任人
  description   VARCHAR(500),
  ext           TEXT,
  created_at    DATETIME     NOT NULL,
  updated_at    DATETIME     NOT NULL,
  CONSTRAINT uk_node_code UNIQUE (code)
);
CREATE INDEX idx_node_type ON node (node_type);
CREATE INDEX idx_node_name ON node (name);

-- 路网边（站点间有向连接，支持分岔/汇合）
CREATE TABLE relation (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_node_id  BIGINT       NOT NULL,
  to_node_id    BIGINT       NOT NULL,
  relation_type VARCHAR(30),            -- DATA_FLOW/API/SUBSCRIBE/APPROVAL...
  level         VARCHAR(4)   DEFAULT 'L3',
  description   VARCHAR(500),
  status        VARCHAR(20)  DEFAULT 'ACTIVE',
  created_at    DATETIME     NOT NULL,
  updated_at    DATETIME     NOT NULL
);
CREATE INDEX idx_relation_from ON relation (from_node_id);
CREATE INDEX idx_relation_to ON relation (to_node_id);

-- 流程（起点→终点）
CREATE TABLE process (
  id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(100) NOT NULL,
  code           VARCHAR(50),
  scene          VARCHAR(20)  DEFAULT 'BUSINESS',  -- DATA/BUSINESS/MANUFACTURING
  start_node_id  BIGINT,
  end_node_id    BIGINT,
  level          VARCHAR(4)   DEFAULT 'L3',
  description    VARCHAR(500),
  status         VARCHAR(20)  DEFAULT 'ACTIVE',
  created_at     DATETIME     NOT NULL,
  updated_at     DATETIME     NOT NULL,
  CONSTRAINT uk_process_code UNIQUE (code)
);

-- 路线（从路网定义的一条完整路径）
CREATE TABLE route (
  id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  process_id  BIGINT       NOT NULL,
  name        VARCHAR(100),
  priority    VARCHAR(20)  DEFAULT 'ALTERNATE',  -- DEFAULT/RECOMMENDED/ALTERNATE
  level       VARCHAR(4)   DEFAULT 'L3',
  description VARCHAR(500),
  status      VARCHAR(20)  DEFAULT 'ACTIVE',
  created_at  DATETIME     NOT NULL,
  updated_at  DATETIME     NOT NULL
);
CREATE INDEX idx_route_process ON route (process_id);

-- 路线站点（有序，含该环节标准时长 SLA，卡点判定依据）
CREATE TABLE route_node (
  route_id     BIGINT NOT NULL,
  seq          INT    NOT NULL,
  node_id      BIGINT NOT NULL,
  expected_duration_ms BIGINT,          -- SLA：该环节标准时长
  PRIMARY KEY (route_id, seq)
);
CREATE INDEX idx_route_node_node ON route_node (node_id);

-- 检测点（每个站点可挂多个）
CREATE TABLE checkpoint (
  id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  node_id    BIGINT       NOT NULL,
  name       VARCHAR(100),
  kind       VARCHAR(20)  DEFAULT 'CUSTOM',  -- DEFAULT 系统默认 / CUSTOM 自定义
  check_type VARCHAR(30),   -- DATA_VOLUME/FRESHNESS/DELAY/INTEGRITY/SERVICE_STATUS/SQL/SCRIPT/THRESHOLD
  params     TEXT,          -- 规则参数（阈值/SQL/频率等）
  freq       VARCHAR(20)  DEFAULT '5m',
  level      VARCHAR(4)   DEFAULT 'L3',
  enabled    TINYINT      DEFAULT 1,
  created_at DATETIME     NOT NULL,
  updated_at DATETIME     NOT NULL
);
CREATE INDEX idx_checkpoint_node ON checkpoint (node_id);

-- 检测结果（留痕）
CREATE TABLE check_result (
  id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  checkpoint_id BIGINT      NOT NULL,
  instance_id   BIGINT,
  check_time    DATETIME    NOT NULL,
  status        VARCHAR(20),            -- PASS/FAIL/TIMEOUT/SKIP
  `value`       TEXT,                   -- 列名 value 为 H2 保留关键字，反引号引用（MySQL 下无需引号）
  message       VARCHAR(500)
);
CREATE INDEX idx_result_ckpt ON check_result (checkpoint_id);
CREATE INDEX idx_result_time ON check_result (check_time);

-- ==================== 监控域 ====================

-- 流程实例（一次真实运行）
CREATE TABLE instance (
  id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  process_id       BIGINT,
  route_id         BIGINT,
  biz_no           VARCHAR(50),         -- 业务单号/流水号
  biz_name         VARCHAR(100),        -- 业务别名（显示名）
  start_time       DATETIME,
  end_time         DATETIME,
  status           VARCHAR(20),         -- RUNNING/SUCCESS/FAIL/STUCK/TIMEOUT
  current_node_id  BIGINT,
  total_duration_ms BIGINT,
  source           VARCHAR(20)  DEFAULT 'MANUAL',  -- INFER特征推断/MANUAL人工/REPORT进度上报/API
  created_at       DATETIME    NOT NULL,
  updated_at       DATETIME    NOT NULL
);
CREATE INDEX idx_instance_bizno ON instance (biz_no);
CREATE INDEX idx_instance_status ON instance (status);
CREATE INDEX idx_instance_route ON instance (route_id);

-- 实例经过的站点（每环节耗时/状态）
CREATE TABLE instance_node (
  id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instance_id   BIGINT      NOT NULL,
  node_id       BIGINT      NOT NULL,
  seq           INT,
  arrive_time   DATETIME,
  leave_time    DATETIME,
  duration_ms   BIGINT,
  status        VARCHAR(20),
  message       VARCHAR(500)
);
CREATE INDEX idx_inst_node_instance ON instance_node (instance_id);

-- 告警
CREATE TABLE alert (
  id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_type    VARCHAR(30),            -- STUCK/FAIL/TIMEOUT/CHECK_FAIL
  target_type   VARCHAR(20),            -- NODE/INSTANCE/ROUTE/PROCESS
  target_id     BIGINT,
  message       VARCHAR(500),
  severity      VARCHAR(10),
  disposition   VARCHAR(50),            -- NOTIFY/TICKET/AUTO_ACTION（逗号组合）
  status        VARCHAR(20)  DEFAULT 'OPEN',
  created_at    DATETIME    NOT NULL,
  resolved_at   DATETIME
);
CREATE INDEX idx_alert_status ON alert (status);
CREATE INDEX idx_alert_target ON alert (target_type, target_id);

-- 工单
CREATE TABLE ticket (
  id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_id      BIGINT      NOT NULL,
  assignee      VARCHAR(50),
  priority      VARCHAR(10),
  status        VARCHAR(20) DEFAULT 'OPEN',  -- OPEN/PROCESSING/RESOLVED
  description   VARCHAR(500),
  created_at    DATETIME   NOT NULL,
  resolved_at   DATETIME
);
CREATE INDEX idx_ticket_alert ON ticket (alert_id);
CREATE INDEX idx_ticket_assignee ON ticket (assignee);

-- ==================== 配置域 ====================

-- 配置版本（全配置对象留痕）
CREATE TABLE config_version (
  id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_type   VARCHAR(30) NOT NULL,   -- PROCESS/NODE/ROUTE/CHECKPOINT/CONNECTOR...
  target_id     BIGINT      NOT NULL,
  version       INT         NOT NULL,
  content       TEXT,                   -- 该版本完整配置快照
  change_note   VARCHAR(500),
  operator      VARCHAR(50),
  status        VARCHAR(20),            -- DRAFT/PENDING_APPROVAL/PUBLISHED/ROLLED_BACK
  created_at    DATETIME   NOT NULL,
  CONSTRAINT uk_version UNIQUE (target_type, target_id, version)
);

-- 命名别名（通用，任意对象可加）
CREATE TABLE alias (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_type   VARCHAR(30)  NOT NULL,  -- PROCESS/ROUTE/INSTANCE/NODE/VIEW/CHECKPOINT
  target_id     BIGINT       NOT NULL,
  name          VARCHAR(100) NOT NULL,
  is_primary    TINYINT      DEFAULT 0, -- 是否主显示名
  created_at    DATETIME     NOT NULL
);
CREATE INDEX idx_alias_target ON alias (target_type, target_id);
CREATE INDEX idx_alias_name ON alias (name);

-- ==================== 接入域 ====================

-- 连接器（数据源接入，可插拔）
CREATE TABLE connector (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connector_type VARCHAR(20),           -- DB/EXCEL/CMDB/API/LOG/IOT
  name          VARCHAR(100),
  db_type       VARCHAR(20),            -- MYSQL/ORACLE/PG...
  host          VARCHAR(100),
  port          INT,
  username      VARCHAR(100),
  encrypted_pwd VARCHAR(255),           -- AES 加密存储
  config        TEXT,
  enabled       TINYINT      DEFAULT 1,
  created_at    DATETIME     NOT NULL
);

-- 采集任务
CREATE TABLE import_job (
  id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connector_id  BIGINT,
  job_type      VARCHAR(20),            -- MANUAL/SCHEDULED
  cron          VARCHAR(50),
  status        VARCHAR(20),            -- RUNNING/SUCCESS/FAIL
  summary       VARCHAR(500),
  start_time    DATETIME,
  end_time      DATETIME
);
CREATE INDEX idx_job_connector ON import_job (connector_id);

-- 采集日志
CREATE TABLE import_log (
  id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id        BIGINT,
  level         VARCHAR(10),
  message       VARCHAR(500),
  created_at    DATETIME   NOT NULL
);
CREATE INDEX idx_log_job ON import_log (job_id);

-- ==================== 系统域（RBAC / 审计） ====================

CREATE TABLE sys_user (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      VARCHAR(50)  NOT NULL,
  password_hash VARCHAR(255) NOT NULL,  -- BCrypt
  display_name  VARCHAR(100),
  email         VARCHAR(100),
  status        TINYINT      DEFAULT 1,
  created_at    DATETIME    NOT NULL,
  CONSTRAINT uk_username UNIQUE (username)
);

CREATE TABLE sys_role (
  id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_code     VARCHAR(30) NOT NULL,   -- ADMIN/MODELER/OPERATOR/ONCALL/VIEWER
  role_name     VARCHAR(50),
  description   VARCHAR(200),
  CONSTRAINT uk_role_code UNIQUE (role_code)
);

CREATE TABLE sys_user_role (
  user_id       BIGINT NOT NULL,
  role_id       BIGINT NOT NULL,
  PRIMARY KEY (user_id, role_id)
);

-- 流程/关系网级授权（数据权限）
CREATE TABLE sys_grant (
  id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id       BIGINT      NOT NULL,
  target_type   VARCHAR(20) NOT NULL,   -- PROCESS/VIEW
  target_id     BIGINT      NOT NULL
);
CREATE INDEX idx_grant_role ON sys_grant (role_id);

-- 操作审计
CREATE TABLE operation_log (
  id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operator      VARCHAR(50),
  action        VARCHAR(50),            -- CREATE/UPDATE/DELETE/ROLLBACK/APPROVE...
  target_type   VARCHAR(30),
  target_id     BIGINT,
  detail        TEXT,
  ip            VARCHAR(50),
  created_at    DATETIME   NOT NULL
);
CREATE INDEX idx_oper_time ON operation_log (created_at);
CREATE INDEX idx_oper_operator ON operation_log (operator);
