-- ============================================================
-- V8__correction_and_pattern.sql · H2
-- 图来源 G5 校正闭环：校正记录 + 模式库
-- ============================================================

CREATE TABLE correction_record (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_type   VARCHAR(20)  NOT NULL,  -- NODE/EDGE/ROUTE/PATTERN
  target_id     VARCHAR(255) NOT NULL,
  target_name   VARCHAR(255),
  operation     VARCHAR(20)  NOT NULL,  -- RENAME/CONFIRM/MERGE/ADD/DELETE/REORDER
  old_value     TEXT,
  new_value     TEXT,
  merge_target_id VARCHAR(255),
  reorder_node_ids TEXT,
  status        VARCHAR(20)  DEFAULT 'PENDING',  -- PENDING/APPLIED/REJECTED
  source        VARCHAR(50)  DEFAULT 'MANUAL',    -- ENGINE/LLM/MANUAL
  operator      VARCHAR(100),
  remark        TEXT,
  created_at    DATETIME     NOT NULL,
  updated_at    DATETIME
);
CREATE INDEX idx_correction_target ON correction_record (target_type, target_id);
CREATE INDEX idx_correction_status ON correction_record (status);
CREATE INDEX idx_correction_operator ON correction_record (operator);

CREATE TABLE pattern_library (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pattern_type  VARCHAR(20)  NOT NULL,  -- NODE_NAME/EDGE_NAME/ROUTE_TEMPLATE
  pattern_key   VARCHAR(500) NOT NULL,
  pattern_value TEXT,
  source_type   VARCHAR(20),            -- NODE/EDGE/ROUTE/PATTERN
  source_id     VARCHAR(255),
  source_operation VARCHAR(20),
  hit_count     INT          DEFAULT 0,
  confirmed     TINYINT      DEFAULT 0,
  created_by    VARCHAR(100),
  created_at    DATETIME     NOT NULL,
  updated_at    DATETIME
);
CREATE INDEX idx_pattern_type ON pattern_library (pattern_type);
CREATE INDEX idx_pattern_key ON pattern_library (pattern_key);
CREATE INDEX idx_pattern_confirmed ON pattern_library (confirmed);
