-- ============================================================
-- V9__llm_config.sql · H2
-- G4 大模型接入配置（单行，可界面配置；DB 值覆盖环境变量默认值）
-- ============================================================

CREATE TABLE llm_config (
  id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_key         VARCHAR(20)  NOT NULL DEFAULT 'default',
  base_url           VARCHAR(255),           -- OpenAI 兼容服务地址
  encrypted_api_key  VARCHAR(512),           -- API Key AES-GCM 加密（AesUtil）
  model              VARCHAR(100),
  timeout_ms         INT,
  max_tokens         INT,
  temperature        DOUBLE,
  updated_by         VARCHAR(100),
  updated_at         DATETIME
);
CREATE UNIQUE INDEX uk_llm_config_key ON llm_config (config_key);
